export const getMusicStyles = [
  'Arrocha',
  'Axé',
  'Baião',
  'Balada',
  'Beguine',
  'Blues',
  'Bolero',
  'Bolero-Mambo',
  'Bossa Nova',
  'Canção',
  'Canção Militar',
  'Cantigas de Roda',
  'Carimbó',
  'Chá chá chá',
  'Choro',
  'Dance-pop',
  'Dobrado',
  'Erudito',
  'Barroco',
  'Classicismo',
  'Contemporâneo',
  'Modernismo',
  'Renascentista',
  'Romantismo',
  'Estudos',
  'Fantasia',
  'Forró',
  'Fox',
  'Frevo',
  'Funk',
  'Gospel',
  'Guarania',
  'Hinos Católicos',
  'Hinos de Times de Futebol',
  'Hinos Diversos',
  'Hinos e Canções da Marinha do Brasil',
  'Hinos e Canções das Polícias Militares Brasileiras',
  'Hinos e Canções do Exército Brasileiro',
  'Hinos Estaduais',
  'Hinos Evangélicos',
  'Hinos Municipais – BR',
  'Hinos Municipais – CE',
  'Hinos Nacionais',
  'Hinos Oficiais do Brasil',
  'Jazz',
  'Jovem Guarda',
  'Kuduro',
  'Lambada',
  'Latin-Jazz',
  'Mambo',
  'Maracatu',
  'Marcha',
  'Marcha de Procissão',
  'Marcha Fúnebre',
  'Marcha Junina',
  'Marcha Rancho',
  'Marchinhas de Carnaval',
  'Maxixe',
  'Mazurca',
  'Milonga',
  'MPB',
  'Música Eletrônica',
  'Música Programática',
  'Natalinas',
  'Pagode',
  'Passo Doble',
  'Polaca',
  'Polka',
  'Pop',
  'Pot-pourri',
  'Quadrilha',
  'Ragtime',
  'Recitativo',
  'Reggae',
  'Rock',
  'Romance',
  'Rumba',
  'Salsa',
  'Samba',
  'Schottisch',
  'Serenata',
  'Sertanejo',
  'Suíte',
  'Swing',
  'Tango',
  'Tango Brasileiro',
  'Toada',
  'Toccata',
  'Tradicional',
  'Trilha Sonora',
  'Valsa',
  'Vaneira',
  'Xote',
].map((item) => ({
  label: item,
  value: item,
}));
